name = "elohimstudio"
account_id = "618eff06f5fe8b901b52c935582083d2"
compatibility_date = "2025-03-20"

[site]
bucket = "./public"
entry-point = "./src"

route = "elohimstudio.co/*"
workers_dev = false